### ISSUE TITLE
[Feature] General content blocks

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/content-service#11]
The idea behind it is to support general blocks that will be injected in several places of the frontend...
The admin can use it to insert ads, free texts, etc..

Every block can be one of selected types:
1. free text (using WYSIWYG).
2. free text (as HTML editor).
3. list of strings (admin-panel frontend will use this option to upload images and insert the URLs).

Each content block should have a name as a unique key and identifier for API,  its type (enum), and also a display text and description (that are only available for privileged roles).

**Comment by davidmeirlevy** [comment]
expected schema:
name: string, required.
tenant: string, required.
description: string, for editors only.
contents: Array of anything.
contentType: enum(content, images, script)

**Comment by itays123** [comment]
In my opinion we should use markdown (.md) style, like reddit posts and comments and github.
It's also way easier to implement and convert to html with a javascript library called 'marked'.
I have done it myself a few weeks ago in a [newspaper website I made](https://github.com/itays123/point-of-vue)

**Comment by itays123** [comment]
we could add this type to the contentType enum as well

**Comment by davidmeirlevy** [comment]
we already have a wysiwyg component, so the HTML type is not hard.
also, you should consider regular editors and bloggers (not developers) that aren't familiar with markdown syntax, and that want real rich abilities, that we already developed in the admin-panel.

**Comment by itays123** [comment]
So what exactly do you mean by html type? Yoy want to provide an html editor in admin and accept html strings in the `POST api/post` route?

**Comment by davidmeirlevy** [comment]
@itays123 reddit probably doesn't want users to enter HTML tags into their content.
it's ok to approve HTML content from an editor with permission to the admin-panel, but for example - it's not a good idea to allow full HTML content from posts comments of regular users.

**Comment by itays123** [comment]
makes sense.
so what do we need to do?

- [ ] accept html in the createPost() and updatePost() controllers. do you want the html to be saved as is in mongoDB?

- [ ] pass the block type in the response (headers or body)

**Comment by davidmeirlevy** [comment]
general content blocks should be new sources, like posts / categories / menus.
all its content should be stored in DB, in a new model.

**Comment by itays123** [comment]
on it.

**Comment by itays123** [comment]
I think I get it now.
Those blocks are **independent from posts, just featuring on the website**. First I thought they were just another way to write posts.
I created another branch with the work on this feature

**Comment by davidmeirlevy** [comment]
👍 
Exactly.
The editor / admin will use it for side contents, repeated contents, advertisements. footer content, etc.

**Comment by itays123** [comment]
We need to implement this feature in admin-panel and blog-front too, right?

**Comment by davidmeirlevy** [comment]
Yes. But it’s for another task :)

**Comment by davidmeirlevy** [comment]
This will damage the purpose of RESTful API.
Maybe we should consider moving to GQL API in the future.

**Comment by itays123** [comment]
I love graphql. It's much more useful and right for complex apps, like REST replaced SOAP.

What I asked was if we could create an algorithm the merges the two arrays in a random order and returns one array, so we won't have to do this on the frontend.

**Comment by davidmeirlevy** [comment]
That will be for another phase..

**Comment by itays123** [comment]
Ok. So I'll close the issue and send a pull

**Comment by davidmeirlevy** [comment]
We will close this issue after the PR will be merged..

**Comment by itays123** [comment]
OK. I'll commit the changes requested soon
