### ISSUE TITLE
[ Feature ] Create endpoint to watch all the posts written by specific author 

### ISSUE THREAD

**Issue by drorrose** [greenpress/content-service#17]
The endpoint should receive author id and will return a list of all the posts written by that author

**Comment by ShiraRotman** [comment]
Is anyone working on this? If not, I can start.

**Comment by davidmeirlevy** [comment]
@ShiraRotman got for it. thanks.

**Comment by davidmeirlevy** [comment]
the route should be:
`GET /api/author/:authorId/posts`
return expected result is an array of posts, with:
_id, path, title, short, tags, authors, category{_id, name, path}

**Comment by ShiraRotman** [comment]
Is there supposed to be an authors table?

**Comment by davidmeirlevy** [comment]
Done by @ShiraRotman
